### PR TITLE
main: sanitize transition configuration values

### LINKED ISSUE #206: puppeth: YOLOv1 nil pointer dereference
puppeth panics when configuring new genesis.

#### System information

Geth version: `geth version`
OS & Version: Linux
Commit hash : a3b5c762376c8ceec388d238d293c9ef76bd6549

#### Expected behaviour

no panic

#### Actual behaviour

panic

#### Steps to reproduce the behaviour

create new genesis with puppeth.
configure new genesis.
answer questions until YOLOv1 block.

#### Backtrace

````
Which block should YOLOv1 (EIP2537) come into effect? (default = <nil>)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x869fe4]

goroutine 1 [running]:
main.(*wizard).manageGenesis(0xc000150100)
        github.com/ethereum/go-ethereum/cmd/puppeth/wizard_genesis.go:244 +0x1804
main.(*wizard).run(0xc000150100)
        github.com/ethereum/go-ethereum/cmd/puppeth/wizard_intro.go:149 +0xa08
main.runWizard(0xc0001269a0, 0x3, 0xf69fe0)
        github.com/ethereum/go-ethereum/cmd/puppeth/puppeth.go:63 +0x27a
gopkg.in/urfave/cli%2ev1.HandleAction(0x8de200, 0x9b94c0, 0xc0001269a0, 0xc000078780, 0x0)
        gopkg.in/urfave/cli.v1@v1.20.0/app.go:490 +0xc8
gopkg.in/urfave/cli%2ev1.(*App).Run(0xc0001096c0, 0xc0000201e0, 0x1, 0x1, 0x0, 0x0)
        gopkg.in/urfave/cli.v1@v1.20.0/app.go:264 +0x5dd
main.main()
        github.com/ethereum/go-ethereum/cmd/puppeth/puppeth.go:54 +0x24b
````

### PR DESCRIPTION
**Pull request by meowsbits**
Program paniced when attempting to take the value
of a nil address.

Fixes https://github.com/etclabscore/core-geth/issues/206

Signed-off-by: meows <b5c6@protonmail.com>

### CODE REVIEW

**Comment by meowsbits** [comment]
Works now, tested as:

```
 2. Manage existing genesis
 3. Track new remote server
 4. Deploy network components
> 2

 1. Modify existing configurations
 2. Export genesis configurations
 3. Remove genesis configuration
> 1

Which block should Homestead come into effect? (default = 18446744073709551615)
> 0

Which block should EIP150 (Tangerine Whistle) come into effect? (default = 0)
> 0

Which block should EIP155 (Spurious Dragon) come into effect? (default = 0)
>

Which block should EIP158/161 (also Spurious Dragon) come into effect? (default = 0)
>

Which block should Byzantium come into effect? (default = 18446744073709551615)
>

Which block should Constantinople come into effect? (default = 18446744073709551615)
>

Which block should Petersburg come into effect? (default = 0)
>

Which block should Istanbul come into effect? (default = 0)
>

Which block should YOLOv1 (EIP2537) come into effect? (default = 18446744073709551615)
> 14
Chain configuration updated:

{
  "chainId": 69,
  "homesteadBlock": 0,
  "eip150Block": 0,
  "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "eip155Block": 0,
  "eip158Block": 0,
  "byzantiumBlock": 0,
  "constantinopleBlock": 0,
  "petersburgBlock": 0,
  "istanbulBlock": 0,
  "yoloV1Block": 14,
  "clique": {
    "period": 15,
    "epoch": 30000
  },
  "trustedCheckpoint": null,
  "trustedCheckpointOracle": null
}

What would you like to do? (default = stats)
 1. Show network stats
 2. Manage existing genesis
 3. Track new remote server
 4. Deploy network components
```

**Comment by BelfordZ** [comment]
It seems more ideal that if configs can be defaulted before being used such that a config value is never `nil`. Is there anyway to default the configuration values before they arrive to this code?

**Comment by meowsbits** [comment]
As it were, instead of pursuing fixes and improvements to this code, I would propose considering ejecting it from the repository. 

My reasons being: I don't like interactive command line anythings. And, everything that `puppeth` does can be done in other ways.

**Comment by BelfordZ** [comment]
yeah that would be solid.

**Comment by ziogaschr** [comment]
I tested it. LGTM

**Pull request merged**
