### PR TITLE
Update algorithm.go

### PR DESCRIPTION
**Pull request by yuriy0803**
Set the number of threads to 2  ?????????

### CODE REVIEW

**Comment by meowsbits** [comment]
Why?

**Comment by yuriy0803** [comment]
> Why?

because it is the next DAG size where the CPU runs at 100% Generating ethash verification cache

**Comment by yuriy0803** [comment]
What other programs can cause problems until it generates the Ethash verification cache?

**Comment by yuriy0803** [comment]
when CPU is running at 100%

**Comment by ziogaschr** [comment]
While I see your point, as you see 100% CPU usage for a while, I wouldn't favour this change. The Ethash generation takes short time (1-5 minutes), which is considered ok to utilise the max number of CPU threads available to the system. The system handles its resources for other apps.

**Comment by meowsbits** [comment]
It seems this proposal has been resolved as unnecessary by @ziogaschr's clarification.

**Pull request closed without merging**
