### PR TITLE
Merge/foundation release/1.9 20201229 2

### PR DESCRIPTION
**Pull request by meowsbits**
Merges upstream [ethereum/go-ethereum v1.9.25](https://github.com/ethereum/go-ethereum/releases/tag/v1.9.25).

The pull request's base is `next`, which is a branch that should be parallel and even with `master`. This allows time for merge conflict resolution and stability testing before the upstream change set hits master. This also allows time and space for cherry-picking (or making) hotfixes.

The diff at the _merge conflict resolution_ state was: https://gist.github.com/meowsbits/b0505d3416392d484a405af6f8656352.
I included this diff in the commit message of https://github.com/etclabscore/core-geth/pull/272/commits/a17020d99a938732aef13f79e315b835a6ffc556.

### CODE REVIEW

**Comment by ziogaschr** [comment]
@meowsbits I like that you kept the diff with the conflicts so as anyone can check it. I wonder if adding it in the commit message for bigger diffs will create any issues in future.

**Comment by meowsbits** [comment]
Yea, I don't know if huge commit messages are problematic. Not that I'm aware of yet, except that
- Github truncates it
- Jetbrains' GoLand truncates it

I spent some time trying to figure out a cleaner way of handling it, and would still like to improve the system. But it seems tricky... there's [`git-bottle`](https://github.com/da-x/git-bottle) which seems to tackle a similar issue, but that's about as close as I've found to a solution to conflict and resolution tracking.  

For now I figured including the diff would provide the essential information, although making it useful still requires some thought/massaging.

**Comment by ziogaschr** [comment]
Thinking out loud, and I am not a huge fun of the ideas either.

1. Keep the file diff, add/commit after resolve + 2nd commit to remove it. (I don't like the extra commits)
2. Create an issue or comment in the merge PR with the diff and then add link to it in the commit message as you did

**Comment by meowsbits** [comment]
@ziogaschr @iquidus This LGTM. Finished a successful complete `--classic` sync and some other continuity and CLI tests. No failures.

**Review by iquidus — APPROVED** [review]

**Pull request merged**
