### PR TITLE
README.md:update readme file 

### PR DESCRIPTION
**Pull request by eyfl**
Update the description in readme file to align with the new brand

### CODE REVIEW

**Review by meowsbits — APPROVED** [review]
LGTM. 

Maybe we should consider simply dropping the `etclabscore/go-ethereum` column since it is indeed obsolete, and thus a comparison against it obsolete as well ?

**Comment by eyfl** [comment]
> LGTM.
> 
> Maybe we should consider simply dropping the `etclabscore/go-ethereum` column since it is indeed obsolete, and thus a comparison against it obsolete as well ?

make sense, `etclabscore/go-ethereum`  got removed.

**Review by meowsbits — COMMENTED** [review]
Some of the badges on top haven't been updated:
- `API Reference` ref
- `Gitter` ref (we don't have a Gitter set up? maybe should do that...?)
- `Code Shelter` - doesn't apply here

**Comment by eyfl** [comment]
Per @meowsbits 's suggestion, create new Gitter community for core-geth, also update  API reference

**Pull request merged**
