### PR TITLE
Feat/ecip1100 nodisable

### PR DESCRIPTION
**Pull request by meowsbits**
Rel #299 and #303. Compared to 303, https://github.com/etclabscore/core-geth/commit/04b886d6b9bcaae5a521eb975e9ecfe914c6734e is the only unique commit.

This is a(nother) possible iteration of approaches to configuring the deactivation of ECBP1100 auto-shutoff mechanisms.

It uses the flag `--ecbp1100.nodisable`, a `bool` flag that, if set, is by default truthy, and prevents the efficacy of auto-shutoff logic, _but does not force activation_, of ECBP1100. That is, the node will start and sync following existing behavior without ECBP1100 enabled, but once achieving sync with a best peer and then enabling ECBP1100, shutoff mechanisms based on minimum peers or stale heads will be inoperative.

### CODE REVIEW

**Comment by meowsbits** [comment]
https://github.com/etclabscore/core-geth/pull/304/commits/cd85e71e4357395a962aec94512a8213a9fb5aac adds a test showing that the min peers floor shutoff mechanism is disabled (confusingly, the disablement mechanism is disabled, ie `nodisable`).

**Comment by meowsbits** [comment]
I just closed #209 and #303, both being alternative designs and implementations, in favor of this one.

**Review by ziogaschr — APPROVED** [review]
LGTM! 
I verified the logic and tried to sync with/without this option set. 
It's hard to reproduce this with nodes, so we trust the tests (thx for your latest addition).

**Comment by meowsbits** [comment]
CI failed was a test [`TestClientCancelWebsocket`](https://travis-ci.org/github/etclabscore/core-geth/jobs/755172067#L858). Merging.

**Comment by meowsbits** [comment]
CI failed was a test [`TestClientCancelWebsocket`](https://travis-ci.org/github/etclabscore/core-geth/jobs/755172067#L858). Merging.

**Pull request merged**
