### PR TITLE
Merge/drossix blue+pink marble

### LINKED ISSUE #93: pull latest ethereum/go-ethereum
Especially rpc/ and node/ package changes; I want to diff #90 against an updated head (that changeset currently includes a lot of "irrelevant" changes there which distract from the simplicity of the implementation ;).

### PR DESCRIPTION
**Pull request by meowsbits**
Fixes #93 

Merges ethereum/go-ethereum through 3666da8a4b, a commit made at ethereum/go-ethereum from May 14 around 11UTC,  including changes from Drossix Blue and Pink Marble releases.

### CODE REVIEW

**Comment by meowsbits** [comment]
~~Only the lint step is failing. It's failing because of a strange timeout. https://travis-ci.org/github/etclabscore/core-geth/jobs/683550806#L253
The command works for me locally, so I think this is a(nother) CI-specific issue, and not related to any actual linting issue.~~

Fixed. See below.

**Comment by meowsbits** [comment]
Last couple of commits
- bump Travis Go version to v1.14.x (Appveyor was already there)
- bump [`golangci-lint`](https://github.com/golangci/golangci-lint) to v1.26.0
- bump golangci-lint timeout `--timeout 3m0s`, which resolves https://github.com/etclabscore/core-geth/pull/96#issuecomment-624618539

**Comment by meowsbits** [comment]
Update: now includes changeset through latest master, including the Pink Marble release.

**Review by tzdybal — APPROVED** [review]
I reviewed your commits @meowsbits, LGTM. :+1:

**Pull request merged**
