### PR TITLE
Release/v1.9.10

### PR DESCRIPTION
**Pull request by meowsbits**
This'll be the first release under the new `core-geth` namespace... we'll see how the CI does :crossed_fingers: 

---

_Release notes draft_

> https://github.com/etclabscore/core-geth/releases

### Buffalo Buffalo Buffalo (v1.9.10)

- [x] Implements [ECIP1086](https://github.com/ethereumclassic/ECIPs/blob/master/_specs/ecip-1086.md). This specification is an allowance provisioning for ETC testnets Kotti and Mordor to continue to [incorrectly implement EIP2200](https://github.com/etclabscore/core-geth/commit/0cd6b91457f113d736301c6d08527d394d3b461f). Alternatively, the networks can be rolled back to a point prior to their implementation of EIP2200. [There is not firm human consensus on this issue yet (via the _Discussion-To_ link in ECIP1086)](https://github.com/ethereumclassic/ECIPs/issues/262). However, in balancing the needs to correctly implement things, to break as few things as possible, and to try to keep people on-board, we've decided to publish the ECIP1086 implementation "optimistically." This allows core-geth to not cause a fork on these testnets, and -- importantly -- does not preclude the option of rolling them back (in which case we'll simply remove the ECIP1086 feature as dead code).

- [x] As related above, implements the [EIP2200 gas cost fix](https://github.com/etclabscore/core-geth/commit/0cd6b91457f113d736301c6d08527d394d3b461f).

- [x] Implements [ECIP1078](https://github.com/ethereumclassic/ECIPs/blob/master/_specs/ecip-1078.md) _on ETC testnets Kotti and Mordor only_. Similar in logic to above, this is a compromise between specification and implementation timelines (since `Last Call` period end is after activation on these testnets, see [this PR](https://github.com/etclabscore/multi-geth-fork/pull/145) for some discussion on this).

- [x] And last but not least (as you may have already surmised :wink:) _renames the project to __Core-Geth___!
    - With significant development effort already invested (now approaching 800 commits ahead of our comrade and predecessor [multi-geth/multi-geth](https://github.com/multi-geth/multi-geth)), and an intention to continue growth, we think it's about the right time to fly our own flag. The aim is for this code base and the software it provides to continue serving ETC and entire Eth<sup>n</sup> ecosystem reliably and innovatively. We hope that renaming won't be a cause of political contention, but instead add another optimistic rallying point for configuration-freedom and an extensible, accessible Ethereum-as-protocol. :rocket:

### CODE REVIEW

**Comment by meowsbits** [comment]
:alien: :champagne: I think the CI passed and artifacts all uploaded. On the first try.

**Review by eyfl — APPROVED** [review]
LGTM

**Comment by soc1c** [comment]
Would like to bump to 1.10.0 as discussed in https://github.com/etclabscore/core-geth/issues/1 https://github.com/etclabscore/multi-geth-fork/issues/153

**Comment by meowsbits** [comment]
Oh shoot @soc1c -- I'm sorry! I didn't see your comment here (I merged and pushed from command line).

**Comment by soc1c** [comment]
No worries. We can just author another release

**Comment by meowsbits** [comment]
So for the MINOR version bump rationale, are you thinking that the backwards-compatible functionality is the (re)name? (I can agree with that).

_EDIT_: Ah, I think I misunderstood; thinking now that you meant v1.10.0 with the "classic first" change, or?

**Comment by meowsbits** [comment]
Thinking about this... I think we should consider ECIP1078 implementation a backwards-compatible feature (as well as possilbly 1086 too), and thus we should actually tag the release v1.10.0.

**Comment by meowsbits** [comment]
And since it coincides with the renaming and the associated "significance" of that, I think that resonates intuitively.

**Comment by soc1c** [comment]
exactly :)

**Pull request merged**
