### PR TITLE
p2p/nat: skip TestUPNP in non-CI envs if discover fails

### PR DESCRIPTION
**Pull request by meowsbits**
https://github.com/ethereum/go-ethereum/issues/21476

Date: 2021-05-13 12:33:01-05:00
Signed-off-by: meows <b5c6@protonmail.com>

### CODE REVIEW

**Review by ziogaschr — APPROVED** [review]
Great to have this in! Thanks

**Comment by meowsbits** [comment]
I just added the `pending upstream` label; let's see what the folks at EF think about it, too.

**Comment by meowsbits** [comment]
No word from EF yet. Going ahead with merge.

**Comment by ziogaschr** [comment]
SGTM

**Comment by meowsbits** [comment]
Just rebased on the base branch to give the CIs a second chance.

**Pull request merged**
