### PR TITLE
implementing PR #23558 from ethereum/go-ethereum

### PR DESCRIPTION
**Pull request by afmsavage**
Cloning the changes made https://github.com/ethereum/go-ethereum/pull/23558 to core-geth.

### CODE REVIEW

**Comment by meowsbits** [comment]
Thanks @afmsavage. Looking good. Is it possible to `cherry-pick` the commit(s) to keep code provenance and ensure exact same changes? (Not sure; might be conflicts or other reasons why not..?)

Rel #412

**Comment by ziogaschr** [comment]
Thanks @afmsavage. I would like to test some stuff on this PR which might break the `trace_*` API added on core-geth.

This (testing) will be done soon enough either way, while merging upstream changes.

**Comment by afmsavage** [comment]
Yea no problem @ziogaschr .  I will try to `cherry-pick` from the `go-ethereum` PR but i think there were a few things that didn't exist in this repo VS the `go-ethereum` one, but I'll try what I can.

**Comment by ziogaschr** [comment]
Thanks @afmsavage, we already found an issue and we fixed that. I will test a bit more.

**Comment by afmsavage** [comment]
Ok I was able to cherry pick the PR from go-ethereum but its pretty different.  I commited it so the history is there though.

**Review by meowsbits — APPROVED** [review]

**Comment by ziogaschr** [comment]
LGTM!!!

**Pull request merged**
